# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
identifier = "creators"
name = "Creators"
url = "/creators"

[main.params]
icon = "writing"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/DukeRupert/manifold-creative-collective"

[social.params]
icon = "brand-github"

[[social]]
identifier = "x"
name = "X"
url = "https://x.com/TheManifoldCC"

[social.params]
icon = "brand-x"

[[social]]
identifier = "patreon"
name = "Patreon"
url = "https://patreon.com"

[social.params]
icon = "brand-patreon"
